export const PLAN_RIDE = 'PLAN_RIDE';
export const ADD_PLAN_RIDE_COMMENT = 'ADD_PLAN_RIDE_COMMENT';
export const SET_RIDE_DATE = 'SET_RIDE_DATE';
export const SET_PAYMENT = 'SET_PAYMENT';
export const SET_WALLETID = 'SET_WALLETID';
export const TOGGLE_PAYMENT_TYPE = 'TOGGLE_PAYMENT_TYPE';
export const TOGGLE_WALLET_ID_SHOW = 'TOGGLE_WALLET_ID_SHOW';
export const SET_OPEN_STATUS = 'SET_OPEN_STATUS';
export const SET_OPEN_TIME = 'SET_OPEN_TIME';


export const ADD_LOCATION_TO_FAV = 'ADD_LOCATION_TO_FAV';
export const REMOVE_LOCATION_FROM_FAV = 'REMOVE_LOCATION_FROM_FAV';

export const SET_FROM_LOCATION = 'SET_FROM_LOCATION';
export const SET_TO_LOCATION = 'SET_TO_LOCATION';
export const SET_STOP_LOCATION = 'SET_STOP_LOCATION';
export const REMOVE_STOP_LOCATION = 'REMOVE_STOP_LOCATION';

export const SET_EXPIRED_OR_UPCOMING = 'SET_EXPIRED_OR_UPCOMING';

export const SET_RATING = 'SET_RATING';
export const SET_RATING_COMMENT = 'SET_RATING_COMMENT';

export const SEARCH_PREDICTIONS = 'SEARCH_PREDICTIONS';
export const FOUND_PREDICTIONS = 'FOUND_PREDICTIONS';

export const FETCH_PREDICITON_PLACE = 'FETCH_PREDICITON_PLACE';
export const RECEIVE_PREDICITON_PLACE = 'RECEIVE_PREDICITON_PLACE';

export const PLANNED_RIDE_REQUEST = 'PLANNED_RIDE_REQUEST';
export const PLAN_RIDE_PLANNED = 'PLAN_RIDE_PLANNED';

export const FETCH_RIDE_SUCCESS = 'FETCH_RIDE_SUCCESS';
export const FETCH_RIDE_REQUEST = 'FETCH_RIDE_REQUEST';

export const CLEAR_PLAN_RIDE = 'CLEAR_PLAN_RIDE';

export const REVIEW_RIDE_SUCCESS = 'REVIEW_RIDE_SUCCESS';
export const REVIEW_RIDE = 'REVIEW_RIDE';

export const SHOW_PRICE = 'SHOW_PRICE';

export const GET_RIDE_PRICE = 'GET_RIDE_PRICE';
export const GOT_RIDE_PRICE = 'GOT_RIDE_PRICE';

export const GOT_RIDE_RATES = 'GOT_RIDE_RATES';
export const GET_RIDE_RATES = 'GET_RIDE_RATES';
export const RATES_ERROR = 'RATES_ERROR';

export const CREATE_AND_FAV_LOCATION = 'CREATE_AND_FAV_LOCATION';
export const PLACE_FAVORITE_MARK = 'PLACE_FAVORITE_MARK';
export const CREATE_AND_FAV_LOCATION_SUCCESS = 'CREATE_AND_FAV_LOCATION_SUCCESS';

export const SET_RIDE_UPDATE_INFO = 'SET_RIDE_UPDATE_INFO';
export const UPDATE_RIDE_SUCCESS = 'UPDATE_RIDE_SUCCESS';
export const UPDATE_RIDE_REQUEST = 'UPDATE_RIDE_REQUEST';

export const PLAN_RIDE_ERROR = 'PLAN_RIDE_ERROR';
