export const SET_SELECTED_EDIT = 'SET_SELECTED_EDIT';
export const TOGGLE_SETTING_SWITCH = 'TOGGLE_SETTING_SWITCH';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const ADDRESS_REMOVED = 'ADDRESS_REMOVED';

export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE';
export const SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE';


export const TOGGLE_PAYMENT_TYPE = 'TOGGLE_PAYMENT_TYPE';
export const TOGGLE_WALLET_ID_SHOW = 'TOGGLE_WALLET_ID_SHOW';
export const TOGGLE_ACCOUNT_TYPE = 'TOGGLE_ACCOUNT_TYPE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

// FORM
export const SET_FORM_PROFILE_IMAGE = 'SET_FORM_PROFILE_IMAGE';
export const CLEAR_PROFILE_UPDATE = 'CLEAR_PROFILE_UPDATE';

// ADDRESSES
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST';

export const SET_CREATE_ADDRESS = 'SET_CREATE_ADDRESS';

export const RECEIVED_ADDRESSES = 'RECEIVED_ADDRESSES';
export const GET_ADDRESSES = 'GET_ADDRESSES';

export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const CLEAR_UPDATE_ADDRESS = 'CLEAR_UPDATE_ADDRESS';

export const RECEIVED_PROFILE_REQUEST = 'RECEIVED_PROFILE_REQUEST';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';

export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';

export const CHANGE_USER_NOTIFICATIONS = 'CHANGE_USER_NOTIFICATIONS';
export const USER_NOTIFICATIONS_CHANGED = 'USER_NOTIFICATIONS_CHANGED';

export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export const EDIT_ADDRESS_LOCATION = 'EDIT_ADDRESS_LOCATION';

export const CHANGE_USER_CONTACT = 'CHANGE_USER_CONTACT';
