export const SET_COUNTRY_CODE = 'SET_COUNTRY_CODE';
export const SET_SELECTED_PROP = 'SET_SELECTED_PROP';
export const SET_PAYMENT_OPTION = 'SET_PAYMENT_OPTION';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_COMPLETED = 'REGISTER_COMPLETED';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const COMPLETE_REGISTER_REQUEST = 'COMPLETE_REGISTER_REQUEST';

export const SET_USER = 'SET_USER';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const STORE_USER_PROFILE = 'STORE_USER_PROFILE';
export const GET_SET_USER_PROFILE = 'GET_SET_USER_PROFILE';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const SET_WALLETS = 'SET_WALLETS';
export const SET_WALLET_NAME = 'SET_WALLET_NAME';
export const SET_WALLETS_AMOUNT = 'SET_WALLETS_AMOUNT';
export const SET_WALLET_ID = 'SET_WALLET_ID';
export const SET_WALLET_ID_PREFERED = 'SET_WALLET_ID_PREFERED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const USER_IDENTIFIED = 'USER_IDENTIFIED';

export const SET_ADDRESS_INFO = 'SET_ADDRESS_INFO';

export const COMPLETE_REGISTER_REQUEST_ERROR = 'COMPLETE_REGISTER_REQUEST_ERROR';

export const RESET_PASSWORD_BY_EMAIL_REQUEST = 'RESET_PASSWORD_BY_EMAIL_REQUEST';
export const PASSWORD_RESET_BY_EMAIL = 'PASSWORD_RESET_BY_EMAIL';

export const SETTING_NEW_ONE_SIGNAL_ID = 'SETTING_NEW_ONE_SIGNAL_ID';
export const SETTING_NEW_ONE_SIGNAL_ID_ERROR = 'SETTING_NEW_ONE_SIGNAL_ID_ERROR';
export const NEW_ONE_SIGNAL_ID_SET = 'NEW_ONE_SIGNAL_ID_SET';
