export { default as Login } from './components/Login';
export { default as Register } from './components/Register';
export { default as RegisterSuccess } from './components/RegisterSuccess';
export { default as Terms } from './components/Terms';
export { default as Privacy } from './components/Privacy';
export { default as ForgotPasswordForm } from './forms/ForgotPasswordForm';
export { default as ForgotPassword } from './components/ForgotPassword';


export { SET_SELECTED_PROP,
	SET_COUNTRY_CODE,
	REGISTER_REQUEST,
	REGISTER_SUCCESS,
	SET_USER,
	SET_USER_TOKEN,
	LOGIN_REQUEST,
	LOGIN_SUCCESS,
	LOGOUT_SUCCESS,
	LOGOUT_REQUEST,
	REMOVE_TOKEN,
	REGISTER_COMPLETED,
	COMPLETE_REGISTER_REQUEST,
	SET_USER_PROFILE,
	SET_PAYMENT_OPTION,
	SET_USER_AVATAR,
	STORE_USER_PROFILE,
	GET_SET_USER_PROFILE,
	SET_WALLETS,
    SET_WALLET_NAME,
    SET_WALLET_ID,
    SET_WALLET_ID_PREFERED,
	SET_WALLETS_AMOUNT,
	LOGIN_FAILURE,
	USER_IDENTIFIED,
	REGISTER_USER_FAILURE,
	SET_ADDRESS_INFO,
	COMPLETE_REGISTER_REQUEST_ERROR,
	RESET_PASSWORD_BY_EMAIL_REQUEST,
	PASSWORD_RESET_BY_EMAIL,
	SETTING_NEW_ONE_SIGNAL_ID,
	SETTING_NEW_ONE_SIGNAL_ID_ERROR,
	NEW_ONE_SIGNAL_ID_SET
} from './constants';

export { setSelected,
	setCountryCode,
	registerUser,
	registerUserRequest,
	registerUserSuccess,
	setUser,
	setWallets,
	getWalletName,
	setWalletName,
	setWalletId,
    setPreferedWalletId,
	setWalletCount,
	setUserToken,
	identifyUser,
	loginUser,
	logoutUserRequest,
	logoutUser,
	logoutUserSuccess,
	removeUserToken,
	userCompletedRegister,
	setPaymentOption,
	completeRegisterUser,
	getWallets,
	setUserAvatar,
	storeUserProfile,
	getAndSetUserProfile,
	toggleUserProfile,
	loginUserFailure,
	userIdentified,
	registerUserSuccessRedirect,
	registerUserFailure,
	setAddressInfo,
	completeRegisterUserRequestError,
	resetPasswordByEmailRequest,
	passwordResetByEmail,
	resetPasswordByEmail,
	settingNewOneSignalId,
	settingNewOneSignalIdError,
	newOneSignalIdSet,
	setNewOneSignalId
} from './actions';
